import ecommerceImg from "../../../images/ecommerce.png";

const data = [
  {
    id: 1,
    title: "E-Commerce Website",
    image: ecommerceImg,
    repo_url: "https://github.com/ziad-ahmed22/DollabyReactApp",
    demo_url: "https://ziad-ahmed22.github.io/DollabyReactApp/",
    skills: ["Html", "Css", "React Js", "React Bootstrap", "Redux Toolkit"],
  },
  {
    id: 2,
    title: "Movies Website",
    image: "/images/movies.png",
    repo_url: "https://github.com/ziad-ahmed22/NetflixoReactApp",
    demo_url: "https://ziad-ahmed22.github.io/NetflixoReactApp/",
    skills: ["Html", "Css", "React Js", "React Bootstrap", "Redux Toolkit"],
  },
  {
    id: 3,
    title: "React Todo App",
    image: "/images/todoReact.png",
    repo_url: "https://github.com/ziad-ahmed22/todo-app-react",
    demo_url: "https://ziad-ahmed22.github.io/todo-app-react/",
    skills: ["Html", "Css", "React Js"],
  },
  {
    id: 4,
    title: "Resturant Website",
    image: "/images/resturant.png",
    repo_url: "https://github.com/ziad-ahmed22/Restaurantly",
    demo_url: "https://ziad-ahmed22.github.io/Restaurantly/",
    skills: ["Html", "Css", "Javascript", "Bootstrap"],
  },
  {
    id: 5,
    title: "Ziad World Website",
    image: "/images/ziadWorld.png",
    repo_url: "https://github.com/ziad-ahmed22/templateFourHtmlCssJS",
    demo_url: "https://ziad-ahmed22.github.io/templateFourHtmlCssJS/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 6,
    title: "Dashboard",
    image: "/images/dashboard.png",
    repo_url: "https://github.com/ziad-ahmed22/DashboardHtmlCss",
    demo_url: "https://ziad-ahmed22.github.io/DashboardHtmlCss/",
    skills: ["Html", "Css"],
  },
  {
    id: 7,
    title: "Js Todo App",
    image: "/images/todojs.png",
    repo_url: "https://github.com/ziad-ahmed22/To_Do_Task",
    demo_url: "https://ziad-ahmed22.github.io/To_Do_Task/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 8,
    title: "Gallery With Slider",
    image: "/images/gallery.png",
    repo_url: "https://github.com/ziad-ahmed22/Awsome_Gallery_With_Slider",
    demo_url: "https://ziad-ahmed22.github.io/Awsome_Gallery_With_Slider/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 9,
    title: "Template Three",
    image: "/images/templateThree.png",
    repo_url: "https://github.com/ziad-ahmed22/templateThreeHtmlCss",
    demo_url: "https://ziad-ahmed22.github.io/templateThreeHtmlCss/",
    skills: ["Html", "Css"],
  },
  {
    id: 10,
    title: "Random Key Generator",
    image: "/images/randomKeyGen.png",
    repo_url: "https://github.com/ziad-ahmed22/Random_Key_Generator",
    demo_url: "https://ziad-ahmed22.github.io/Random_Key_Generator/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 11,
    title: "Images Slider",
    image: "/images/slider.png",
    repo_url: "https://github.com/ziad-ahmed22/Image_Slider",
    demo_url: "https://ziad-ahmed22.github.io/Image_Slider/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 12,
    title: "Template Two",
    image: "/images/templateTwo.png",
    repo_url: "https://github.com/ziad-ahmed22/templateTwoHtmlCss",
    demo_url: "https://ziad-ahmed22.github.io/templateTwoHtmlCss/",
    skills: ["Html", "Css"],
  },
  {
    id: 13,
    title: "Js Quiz App",
    image: "/images/quiz.png",
    repo_url: "https://github.com/ziad-ahmed22/Quiz_App",
    demo_url: "https://ziad-ahmed22.github.io/Quiz_App/",
    skills: ["Html", "Css", "Javascript"],
  },
  {
    id: 14,
    title: "Event Comming Page",
    image: "/images/celebration.png",
    repo_url: "https://github.com/ziad-ahmed22/Count_Down_Timer",
    demo_url: "https://ziad-ahmed22.github.io/Count_Down_Timer/",
    skills: ["Html", "Css", "Javascript"],
  },
];

export default data;
